// <auto-generated />
using System;
using ExamContext.PersistanceDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExamContext.PersistanceDatabase.Migrations
{
    [DbContext(typeof(IeltsDBContext))]
    [Migration("20220718081532_1401-04-27")]
    partial class _14010427
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExamContext.Accounting.Domain.AccountingAggregate.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankTransactionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BankTransactionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerAccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsExamParticipantsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaymentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PaymentFinished")
                        .HasColumnType("bit");

                    b.Property<long>("PaymentPriceAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BankTransactionTypeId");

                    b.HasIndex("ExamTypeId");

                    b.ToTable("BankTransaction");
                });

            modelBuilder.Entity("ExamContext.Accounting.Domain.AccountingAggregate.BankTransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankTransactionType");
                });

            modelBuilder.Entity("ExamContext.Accounting.Domain.AccountingAggregate.ExamType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExamType");
                });

            modelBuilder.Entity("ExamContext.General.Domain.MenuAggregate.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentMenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menu");
                });

            modelBuilder.Entity("ExamContext.General.Domain.UserPanelMenuAggregate.UserPanelMenu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentMenuId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPanelMenu");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.IeltsAggregarte.IeltsExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("IeltsExam");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.IeltsAggregarte.IeltsExamPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscontentAmount")
                        .HasColumnType("int");

                    b.Property<Guid>("IeltsExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("PriceAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IeltsExamId");

                    b.ToTable("IeltsExamPrice");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ParticipantsAggregate.IeltsExamParticipants", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IeltsExamOrederNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("IeltsExamParticipantsStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsExamPriceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IeltsExamParticipantsStatusId");

                    b.ToTable("IeltsExamParticipants");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ParticipantsAggregate.IeltsExamParticipantsDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsExamParticipantsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ListeningExamEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ListeningExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ListeningExamIsGive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ListeningExamRegisterDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ListeningExamStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReadingExamEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReadingExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ReadingExamIsGive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadingExamRegisterDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReadingExamStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SpeakingExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("SpeakingExamIsSetSession")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WritingExamEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("WritingExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("WritingExamIsGive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("WritingExamRegisterDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WritingExamStartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IeltsExamParticipantsId");

                    b.ToTable("IeltsExamParticipantsDetail");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ParticipantsAggregate.IeltsExamParticipantsStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IeltsExamParticipantsStatus");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ResualtAggregarte.IeltsResualtLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IeltsResualtLevel");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ResualtAggregarte.UserResualt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("FinalScore")
                        .HasColumnType("real");

                    b.Property<Guid>("IeltsExamParticipantsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsResualtLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<float?>("ListeningScore")
                        .HasColumnType("real");

                    b.Property<float?>("ReadingScore")
                        .HasColumnType("real");

                    b.Property<float?>("SpeakingScore")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float?>("WritingScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IeltsResualtLevelId");

                    b.ToTable("UserResualt");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningExamAggregate.ListeningExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IeltsExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PreVoiceSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TimerMinuties")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VoiceSource")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ListeningExam");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningExamAggregate.ListeningExamQuestionBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ListeningExamSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningExamSectionId");

                    b.ToTable("ListeningExamQuestionBlock");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningExamAggregate.ListeningExamSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ListeningExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningExamId");

                    b.ToTable("ListeningExamSection");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningQuestionAggregate.ListeningQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ListeningExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListeningExamQuestionBlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListeningExamSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ListeningQuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningQuestionTypeId");

                    b.ToTable("ListeningQuestion");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningQuestionAggregate.ListeningQuestionAnswers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ListeningQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ListeningQuestionId");

                    b.ToTable("ListeningQuestionAnswers");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningQuestionAggregate.ListeningQuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ListeningQuestionType");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningUserAnswerAggregate.ListeningUserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsExamParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ListeningExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ListeningUserAnswer");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementExamAggregate.PlacementExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeActivedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlacementExam");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementExamAggregate.PlacementExamPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscontentAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlacementExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PriceAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlacementExamId");

                    b.ToTable("PlacementExamPrice");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementQuestionAggregate.PlacementQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<Guid>("PlacementExamtId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlacementQuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlacementQuestionTypeId");

                    b.ToTable("PlacementQuestion");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementQuestionAggregate.PlacementQuestionAnswers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<Guid>("PlacementQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlacementQuestionId");

                    b.ToTable("PlacementQuestionAnswers");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementQuestionAggregate.PlacementQuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlacementQuestionType");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementUserAnswerAggregate.PlacementUserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("PlacementUserScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlacementUserAnswer");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementUserScoreAggregate.LevelScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<int>("MinScore")
                        .HasColumnType("int");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LevelScore");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementUserScoreAggregate.PlacementUserScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("LevelScoreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlacementExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LevelScoreId");

                    b.ToTable("PlacementUserScore");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingExamAggregate.ReadingExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IeltsExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TimerMinuties")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReadingExam");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingExamAggregate.ReadingExamQuestionBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<Guid>("ReadingExamSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReadingExamSectionId");

                    b.ToTable("ReadingExamQuestionBlock");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingExamAggregate.ReadingExamSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<Guid>("ReadingExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReadingText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReadingExamId");

                    b.ToTable("ReadingExamSection");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingQuestionAggregate.ReadingQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<Guid>("ReadingExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReadingExamQuestionBlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReadingExamSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReadingQuestionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReadingQuestionTypeId");

                    b.ToTable("ReadingQuestion");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingQuestionAggregate.ReadingQuestionAnswers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNo")
                        .HasColumnType("int");

                    b.Property<Guid>("ReadingQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReadingQuestionId");

                    b.ToTable("ReadingQuestionAnswers");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingQuestionAggregate.ReadingQuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReadingQuestionType");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingUserAnswerAggregate.ReadingUserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsExamParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReadingExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ReadingUserAnswer");
                });

            modelBuilder.Entity("ExamContext.Speaking.Domain.SpeakingExamAggregate.SpeakingExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IeltsExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpeakingExam");
                });

            modelBuilder.Entity("ExamContext.Speaking.Domain.SpeakingExamMeetingAggregate.SpeakingExamMeeting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MeetingEndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeetingStartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpeakingExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SpeakingExamMeeting");
                });

            modelBuilder.Entity("ExamContext.Speaking.Domain.SpeakingExamMeetingAggregate.SpeakingExamMeetingReserve", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsExamParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("SpeakingExamMeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SpeakingExamMeetingId");

                    b.ToTable("SpeakingExamMeetingReserve");
                });

            modelBuilder.Entity("ExamContext.Writing.Domain.WritingExamAggregate.WritingExam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IeltsExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TimerMinuties")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WritingExam");
                });

            modelBuilder.Entity("ExamContext.Writing.Domain.WritingExamAggregate.WritingExamSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TimerMinuties")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WritingExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WritingTopic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("WritingExamId");

                    b.ToTable("WritingExamSection");
                });

            modelBuilder.Entity("ExamContext.Writing.Domain.WritingUserAnswerAggregate.WritingUserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IeltsExamParticipantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WritingExamSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("WritingUserAnswer");
                });

            modelBuilder.Entity("ExamContext.Accounting.Domain.AccountingAggregate.BankTransaction", b =>
                {
                    b.HasOne("ExamContext.Accounting.Domain.AccountingAggregate.BankTransactionType", "BankTransactionTypeCurrent")
                        .WithMany("BankTransactionList")
                        .HasForeignKey("BankTransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExamContext.Accounting.Domain.AccountingAggregate.ExamType", "ExamTypeCurrent")
                        .WithMany("BankTransactionList")
                        .HasForeignKey("ExamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankTransactionTypeCurrent");

                    b.Navigation("ExamTypeCurrent");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.IeltsAggregarte.IeltsExamPrice", b =>
                {
                    b.HasOne("ExamContext.Ielts.Domain.IeltsAggregarte.IeltsExam", "IeltsExamCurrent")
                        .WithMany("IeltsExamPriceList")
                        .HasForeignKey("IeltsExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IeltsExamCurrent");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ParticipantsAggregate.IeltsExamParticipants", b =>
                {
                    b.HasOne("ExamContext.Ielts.Domain.ParticipantsAggregate.IeltsExamParticipantsStatus", "IeltsExamParticipantsStatusCurrent")
                        .WithMany("IeltsExamParticipantsList")
                        .HasForeignKey("IeltsExamParticipantsStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IeltsExamParticipantsStatusCurrent");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ParticipantsAggregate.IeltsExamParticipantsDetail", b =>
                {
                    b.HasOne("ExamContext.Ielts.Domain.ParticipantsAggregate.IeltsExamParticipants", "IeltsExamParticipantsCurrent")
                        .WithMany("IeltsExamParticipantsDetailList")
                        .HasForeignKey("IeltsExamParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IeltsExamParticipantsCurrent");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ResualtAggregarte.UserResualt", b =>
                {
                    b.HasOne("ExamContext.Ielts.Domain.ResualtAggregarte.IeltsResualtLevel", "IeltsResualtLevelCurrent")
                        .WithMany("UserResualtList")
                        .HasForeignKey("IeltsResualtLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IeltsResualtLevelCurrent");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningExamAggregate.ListeningExamQuestionBlock", b =>
                {
                    b.HasOne("ExamContext.Listening.Domain.ListeningExamAggregate.ListeningExamSection", "CurrentListeningExamSection")
                        .WithMany("ListeningExamQuestionBlockList")
                        .HasForeignKey("ListeningExamSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentListeningExamSection");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningExamAggregate.ListeningExamSection", b =>
                {
                    b.HasOne("ExamContext.Listening.Domain.ListeningExamAggregate.ListeningExam", "CurrentListeningExam")
                        .WithMany("ListeningExamSectionList")
                        .HasForeignKey("ListeningExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentListeningExam");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningQuestionAggregate.ListeningQuestion", b =>
                {
                    b.HasOne("ExamContext.Listening.Domain.ListeningQuestionAggregate.ListeningQuestionType", "ListeningQuestionTypeCurrent")
                        .WithMany("ListeningQuestionList")
                        .HasForeignKey("ListeningQuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeningQuestionTypeCurrent");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningQuestionAggregate.ListeningQuestionAnswers", b =>
                {
                    b.HasOne("ExamContext.Listening.Domain.ListeningQuestionAggregate.ListeningQuestion", "ListeningQuestionCurrent")
                        .WithMany("ListeningQuestionAnswersList")
                        .HasForeignKey("ListeningQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListeningQuestionCurrent");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementExamAggregate.PlacementExamPrice", b =>
                {
                    b.HasOne("ExamContext.OnlinePlacement.Domain.PlacementExamAggregate.PlacementExam", "PlacementExamCurrent")
                        .WithMany("PlacementExamPriceList")
                        .HasForeignKey("PlacementExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlacementExamCurrent");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementQuestionAggregate.PlacementQuestion", b =>
                {
                    b.HasOne("ExamContext.OnlinePlacement.Domain.PlacementQuestionAggregate.PlacementQuestionType", "PlacementQuestionTypeCurrent")
                        .WithMany("PlacementQuestionList")
                        .HasForeignKey("PlacementQuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlacementQuestionTypeCurrent");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementQuestionAggregate.PlacementQuestionAnswers", b =>
                {
                    b.HasOne("ExamContext.OnlinePlacement.Domain.PlacementQuestionAggregate.PlacementQuestion", "PlacementQuestionCurrent")
                        .WithMany("PlacementQuestionAnswersList")
                        .HasForeignKey("PlacementQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlacementQuestionCurrent");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementUserScoreAggregate.PlacementUserScore", b =>
                {
                    b.HasOne("ExamContext.OnlinePlacement.Domain.PlacementUserScoreAggregate.LevelScore", "LevelScoreCurrent")
                        .WithMany("PlacementUserScoreList")
                        .HasForeignKey("LevelScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LevelScoreCurrent");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingExamAggregate.ReadingExamQuestionBlock", b =>
                {
                    b.HasOne("ExamContext.Reading.Domain.ReadingExamAggregate.ReadingExamSection", "CurrentReadingExamSection")
                        .WithMany("ReadingExamQuestionBlockList")
                        .HasForeignKey("ReadingExamSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentReadingExamSection");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingExamAggregate.ReadingExamSection", b =>
                {
                    b.HasOne("ExamContext.Reading.Domain.ReadingExamAggregate.ReadingExam", "CurrentReadingExam")
                        .WithMany("ReadingExamSectionList")
                        .HasForeignKey("ReadingExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentReadingExam");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingQuestionAggregate.ReadingQuestion", b =>
                {
                    b.HasOne("ExamContext.Reading.Domain.ReadingQuestionAggregate.ReadingQuestionType", "ReadingQuestionTypeCurrent")
                        .WithMany("ReadingQuestionList")
                        .HasForeignKey("ReadingQuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingQuestionTypeCurrent");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingQuestionAggregate.ReadingQuestionAnswers", b =>
                {
                    b.HasOne("ExamContext.Reading.Domain.ReadingQuestionAggregate.ReadingQuestion", "ReadingQuestionCurrent")
                        .WithMany("ReadingQuestionAnswersList")
                        .HasForeignKey("ReadingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReadingQuestionCurrent");
                });

            modelBuilder.Entity("ExamContext.Speaking.Domain.SpeakingExamMeetingAggregate.SpeakingExamMeetingReserve", b =>
                {
                    b.HasOne("ExamContext.Speaking.Domain.SpeakingExamMeetingAggregate.SpeakingExamMeeting", "currentSpeakingExamMeeting")
                        .WithMany("SpeakingExamMeetingReserveList")
                        .HasForeignKey("SpeakingExamMeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("currentSpeakingExamMeeting");
                });

            modelBuilder.Entity("ExamContext.Writing.Domain.WritingExamAggregate.WritingExamSection", b =>
                {
                    b.HasOne("ExamContext.Writing.Domain.WritingExamAggregate.WritingExam", "CurrentWritingExam")
                        .WithMany("WritingExamSectionList")
                        .HasForeignKey("WritingExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentWritingExam");
                });

            modelBuilder.Entity("ExamContext.Accounting.Domain.AccountingAggregate.BankTransactionType", b =>
                {
                    b.Navigation("BankTransactionList");
                });

            modelBuilder.Entity("ExamContext.Accounting.Domain.AccountingAggregate.ExamType", b =>
                {
                    b.Navigation("BankTransactionList");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.IeltsAggregarte.IeltsExam", b =>
                {
                    b.Navigation("IeltsExamPriceList");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ParticipantsAggregate.IeltsExamParticipants", b =>
                {
                    b.Navigation("IeltsExamParticipantsDetailList");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ParticipantsAggregate.IeltsExamParticipantsStatus", b =>
                {
                    b.Navigation("IeltsExamParticipantsList");
                });

            modelBuilder.Entity("ExamContext.Ielts.Domain.ResualtAggregarte.IeltsResualtLevel", b =>
                {
                    b.Navigation("UserResualtList");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningExamAggregate.ListeningExam", b =>
                {
                    b.Navigation("ListeningExamSectionList");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningExamAggregate.ListeningExamSection", b =>
                {
                    b.Navigation("ListeningExamQuestionBlockList");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningQuestionAggregate.ListeningQuestion", b =>
                {
                    b.Navigation("ListeningQuestionAnswersList");
                });

            modelBuilder.Entity("ExamContext.Listening.Domain.ListeningQuestionAggregate.ListeningQuestionType", b =>
                {
                    b.Navigation("ListeningQuestionList");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementExamAggregate.PlacementExam", b =>
                {
                    b.Navigation("PlacementExamPriceList");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementQuestionAggregate.PlacementQuestion", b =>
                {
                    b.Navigation("PlacementQuestionAnswersList");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementQuestionAggregate.PlacementQuestionType", b =>
                {
                    b.Navigation("PlacementQuestionList");
                });

            modelBuilder.Entity("ExamContext.OnlinePlacement.Domain.PlacementUserScoreAggregate.LevelScore", b =>
                {
                    b.Navigation("PlacementUserScoreList");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingExamAggregate.ReadingExam", b =>
                {
                    b.Navigation("ReadingExamSectionList");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingExamAggregate.ReadingExamSection", b =>
                {
                    b.Navigation("ReadingExamQuestionBlockList");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingQuestionAggregate.ReadingQuestion", b =>
                {
                    b.Navigation("ReadingQuestionAnswersList");
                });

            modelBuilder.Entity("ExamContext.Reading.Domain.ReadingQuestionAggregate.ReadingQuestionType", b =>
                {
                    b.Navigation("ReadingQuestionList");
                });

            modelBuilder.Entity("ExamContext.Speaking.Domain.SpeakingExamMeetingAggregate.SpeakingExamMeeting", b =>
                {
                    b.Navigation("SpeakingExamMeetingReserveList");
                });

            modelBuilder.Entity("ExamContext.Writing.Domain.WritingExamAggregate.WritingExam", b =>
                {
                    b.Navigation("WritingExamSectionList");
                });
#pragma warning restore 612, 618
        }
    }
}
